# Generated by Django 4.2.4 on 2023-08-20 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="group",
        ),
    ]
