# Generated by Django 4.2.4 on 2023-08-20 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0002_trait_created_ate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trait",
            old_name="created_ate",
            new_name="created_at",
        ),
    ]
